# version: '3.8'

# services:
#   ts:
#     image: otramaga/imt-microservices:ts
#     volumes:
#       - ./:/app
#     stdin_open: true
#     tty: true 
#     command: bash

version: '3.8'

services:
  ts:
    build:
      context: .
    volumes:
      - ./:/app
    command: bash