version: "3.9"
services:
  mongo:
    image: mongo
    expose:
      - "27017"
    volumes:
      - ./store/data/mongo:/data/db
  store:
    build: ./store
    ports:
      - "8003:80"
  matches:
    build: ./matches
    ports:
      - "8004:80"
