version: "3.9"
services:
  mongo:
    image: mongo
    expose:
      - "27017"
    volumes:
      - ./store/data/mongo:/data/db
  mongoku:
    image: huggingface/mongoku
    ports:
      - "3100:3100"
    environment:
      - MONGOKU_DEFAULT_HOST=mongodb://mongo:27017/
  store:
    build: ./store
    ports:
      - "8003:80"
  matches:
    build: ./matches
    ports:
      - "8004:80"
